# Generated by Django 4.2.7 on 2026-03-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kelishilgan narx')),
                ('status', models.CharField(choices=[('kutilyapti', 'Kutilyapti'), ('kelishilgan', 'Kelishilgan'), ('sotib_olingan', 'Sotib olingan'), ('bekor_qilingan', 'Bekor qilingan')], default='kutilyapti', max_length=20, verbose_name='Status')),
                ('meeting_location', models.CharField(blank=True, max_length=300, verbose_name='Uchrashuv joyi')),
                ('meeting_time', models.DateTimeField(blank=True, null=True, verbose_name='Uchrashuv vaqti')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product', verbose_name='Mahsulot')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
