# Generated by Django 4.2.7 on 2026-03-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, unique=True, verbose_name="Do'kon nomi")),
                ('shop_description', models.TextField(blank=True, verbose_name="Do'kon tavsifi")),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name="Do'kon logosi")),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Sotuvlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sotuvchi profili',
                'verbose_name_plural': 'Sotuvchi profillari',
            },
        ),
    ]
